[Improve] Nested Stacks
neilkuan/cdk-aurora-globaldatabase pull request #1550
Opened 2023-09-12 12:16 UTC by RayZik

Fixes #1549 

- Added support for the Nested Stacks
- Replace a deprecated method
- Add some tests

2023-09-12 12:33 UTC, neilkuan commented
Hi @RayZik . 😇
Nice thanks for this PR. 

This is a huge contribution. 

Could you do "yarn build" at local, before you push commit to this PR?!  :)

2023-09-12 12:36 UTC, RayZik commented
Hey! I already did it :)

<img width="1260" alt="Screenshot 2023-09-12 at 18 35 36" src="https://github.com/neilkuan/cdk-aurora-globaldatabase/assets/22475031/55ed536f-1c34-46f3-bdd6-3af3c3cbea40">

2023-09-12 12:40 UTC, neilkuan commented
> Hey! I already did it :)
> 
> 
> 
> <img width="1260" alt="Screenshot 2023-09-12 at 18 35 36" src="https://github.com/neilkuan/cdk-aurora-globaldatabase/assets/22475031/55ed536f-1c34-46f3-bdd6-3af3c3cbea40">
> 
> 


Awesome I will review this PR later. 

I am eating dinner. 


感謝你😊

2023-09-12 12:42 UTC, aleksey-zikrackiy commented
Okay, I'm open for any comments :)  Have a good dinner!

2023-09-15 07:30 UTC, RayZik commented
@neilkuan Hey! Any updates? :)

2023-09-15 07:32 UTC, neilkuan commented
> @neilkuan Hey! Any updates? :)

Please see code review comments. :)

2023-09-15 07:42 UTC, RayZik commented
@neilkuan 
> Please see code review comments. :)

I'm so sorry, but where can I find it? I don't see them in the conversation.

2023-09-16 00:12 UTC, neilkuan requested changes

2023-09-16 00:13 UTC, neilkuan commented on src/index.ts
> +export class StackParams {
@RayZik hi

2023-09-16 01:38 UTC, RayZik commented on src/index.ts
> +export class StackParams {
@neilkuan Hey! Yep, good catch! We can use node.id and don't worry about unresolved names :)
I've changed to `stack.node.id`, updated tests, and rebuilt locally

2023-09-16 04:54 UTC, RayZik commented on src/index.ts
> +export class StackParams {
@neilkuan But if we use `stack.node.id` we will make breaking changes...

2023-09-16 04:55 UTC, RayZik commented on src/index.ts
> +export class StackParams {
I did it this way so as not to break backward compatibility
```
    const isUnresolved = cdk.Token.isUnresolved(this.fakeStack.stackName);

    this._params = {
      ...
      name: isUnresolved ? this.getRootNode()?.stackName! : this.fakeStack.stackName,
      ...
    };
    ```

2023-09-16 04:56 UTC, RayZik commented on src/index.ts
> +export class StackParams {
Do u really want to do breaking changes?

2023-09-16 05:06 UTC, neilkuan commented on src/index.ts
> +export class StackParams {
Because I think nobody use this constructs library with Nest stack. Yeah, I think you can handle this way to avoid breaking change.

2023-09-16 05:19 UTC, RayZik commented on src/index.ts
> +export class StackParams {
I did it this way so as not to break backward compatibility
```
    const isUnresolved = cdk.Token.isUnresolved(this.fakeStack.stackName);

    this._params = {
      ...
      name: isUnresolved ? this.fakeStack.node.id : this.fakeStack.stackName,
      ...
    };
    ```
    We can do like this. Is it enough?

2023-09-16 05:24 UTC, RayZik commented on src/index.ts
> +export class StackParams {
PS I will add new tests today to prevent this breaking changes in the future

2023-09-16 05:27 UTC, RayZik commented on src/index.ts
> +export class StackParams {
I'm waiting for ur answer -> https://github.com/neilkuan/cdk-aurora-globaldatabase/pull/1550#discussion_r1327906727

Thanks!

2023-09-16 09:11 UTC, neilkuan commented on src/index.ts
> +export class StackParams {
> I'm waiting for ur answer -> [#1550 (comment)](https://github.com/neilkuan/cdk-aurora-globaldatabase/pull/1550#discussion_r1327906727)
> 
> Thanks!

Sorry, reply for late.

How about use this way to check is int nestStack ??
```ts

export class BaseConstruct extends Construct {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const stack = Stack.of(this);
    if (stack.nested) {
      console.log('stackName else', stack.nestedStackParent?.stackName, stack.nestedStackParent?.node.id);
    } else {
      console.log('stackName stack.nested ', stack.stackName, stack.node.id);
    }
    new aws_s3.Bucket(this, 'MyFirstBucket');

  }
}
// for development, use account/region from cdk cli
const stack = new Stack(app, 'cdk-lookup-dev', { env: devEnv });
const nestedStack = new NestedStack(stack, 'cdk-lookup-dev-nest');
new BaseConstruct(stack, 'BaseConstruct');
new BaseConstruct(nestedStack, 'BaseConstruct');
```

```bash
 npx cdk@latest diff
stackName stack.nested  cdk-lookup-dev cdk-lookup-dev
stackName else cdk-lookup-dev cdk-lookup-dev
```

2023-09-16 11:55 UTC, RayZik commented on src/index.ts
> +export class StackParams {
I'm pretty sure, we don't have to use `nestedStackParent.stackName` cuz the user can add some database into one root stack, it means the database identifier will be equal for each db and throw err :)

I'm sure we have to use node.id for nested stacks like this
```
    const { region, account, stackName, nested, node } = cdk.Stack.of(scope);

    this.name = nested ? node.id : stackName;

    console.log('Result:', nested, this.name, stackName);
```

```
Result: true nested-stack ${Token[TOKEN.235]}
```

We can't provide stackName for the nested stack, which means that this value is dynamic.

2023-09-16 12:02 UTC, neilkuan commented on src/index.ts
> +export class StackParams {
yes, I know. 
I just found the `stack.nested` can check the scope is the nested stack.
We will use `node.id`. :)

2023-09-16 12:04 UTC, RayZik commented on src/index.ts
> +export class StackParams {
Great, am I saving this variant? -> https://github.com/neilkuan/cdk-aurora-globaldatabase/pull/1550#discussion_r1327952033

2023-09-16 12:22 UTC, neilkuan commented on src/index.ts
> +export class StackParams {
okay

2023-09-16 14:20 UTC, RayZik commented on src/index.ts
> +export class StackParams {
@neilkuan Hey! Done! Could u pls re-review it?

2023-09-16 14:27 UTC, neilkuan approved these changes
LGTM
Thank you. 
@RayZik 
Thank you for fix this bug.

2023-09-16 14:28 UTC, merged